

name: tracker
save_events: True
stream_events: True
calibration:
    type: NINE_POINTS
    randomize: True
    auto_pace: True
    screen_background_color: black
    target_attributes:
        outer_diameter: .5
        outer_fill_color: black
        outer_line_color: white
        inner_diameter: .22
        inner_stroke_width: 0
        inner_fill_color: white
runtime_settings:
    sampling_rate: 30

